### PR TITLE
Improved the performance of argmax.

### PR DESCRIPTION
**Pull request by kentan**
The fix got almost 2 times faster than current one without loosing the feature of "unique" option.

If we can use elements.max() instead of np.max(elemements), that would get the function much faster.
http://stackoverflow.com/questions/10943088/numpy-max-or-max-which-one-is-faster

### CODE REVIEW

**Comment by ShangtongZhang** [comment]
I think `elements.max()` may be not safe. `elements' may be a built-in list.

**Comment by findmyway** [comment]
In this case, ``elements`` should be transformed into ``np.array`` first, or we will get an empty result.

Also notice that the returned ``candidates`` is ``np.array`` if ``unique`` is set to ``False``.

**Comment by kentan** [comment]
I missed that. Thank you for pointing that. It seems there is no code that use argmax with "False" option and fortunately there is no degradation on the project but I can make another pull request if you want to return list in case of "False" option.

**Comment by ShangtongZhang** [comment]
@findmyway Thanks for your response. I tested the first case, even if `elements` is a built-in list, `np.where` will work well without transformation to `np.array`. My understanding is that `maxValue` is returned by `np.max`, so it's a np type. 

> >>> a = [1., 2.0, 3.0, 2.0]
> >>> b = np.max(a)
> >>> b
> 3.0
> >>> np.where(a == b)
> (array([2]),)
> >>> np.where(a == 3.0)
> (array([], dtype=int64),)
> >>>

**Comment by findmyway** [comment]
Ah, sorry.  I forget that ``np.max`` will return a numpy type.

    In [2]: type(np.max([1., 2.0, 3.0, 2.0]))
    Out[2]: numpy.float64

**Comment by ShangtongZhang** [comment]
Although it does work, I think it will be safer to add `np.asarray`. And although it's ok to return an `np.array`, I think it will be better to return a `list` for the sake of API consistency. Thanks again!

**Pull request merged**
