### PR TITLE
np.argmax

### PR DESCRIPTION
**Pull request by ndvanforeest**
the utils module seems not to be supported in python3. Besides this the argmax is supported in numpy

### CODE REVIEW

**Comment by ShangtongZhang** [comment]
No. Utils module works well in python3. Please follow the usage section in readme page.
And this argmax is different from np.argmax.

**Comment by ndvanforeest** [comment]
Ok. I did not see that in the readme that I had to install utils. Now that I installed it, it works nearly. However I have to replace the line

from utils.utils import * 

to 

from utils import *

And then it works.  Shall I do a pull request for this change?

**Comment by ShangtongZhang** [comment]
No. Readme does not require you to install anything. Just strictly follow the instructions in the usage section in terminal (including which folder to run ```python```), it should work without any changes. If you want to run it in some IDE, you can either set the environment variable of your IDE properly or change the import clause.

**Comment by ndvanforeest** [comment]
Ok, I see. I typically run python in the directory that contains the file. Now things are a bit different, and indeed 

python3 chapter05/Blackjack.py

works

Thanks

**Comment by ndvanforeest** [comment]
Now I see, there is your own utils/utils.py file. I did not anticipate on this, given that there is a python3-utils module.  I have to admit that I did not think of this.

**Pull request closed without merging**
